package co.juandavidpoveda.pruebachuck.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table frase.
 */
public class Frase implements java.io.Serializable {

    private Long id;
    private String icon_url;
    private String url;
    private String value;

    public Frase() {
    }

    public Frase(Long id) {
        this.id = id;
    }

    public Frase(Long id, String icon_url, String url, String value) {
        this.id = id;
        this.icon_url = icon_url;
        this.url = url;
        this.value = value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIcon_url() {
        return icon_url;
    }

    public void setIcon_url(String icon_url) {
        this.icon_url = icon_url;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
